# Generated by Django 3.1.5 on 2021-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineitem', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
